### ISSUE TITLE
asl-menu

### ISSUE THREAD

**Issue by fabltd** [Allan-N/ASL-Install#1]
Hi 

Great project.

In your read me it would be great to mention how to load asl-menu. Took me a few mins to realise its in the root not user account

**Comment by fabltd** [comment]
Supermon fails to install. No error the menu just returns. Any way to debug?

**Comment by Allan-N** [comment]
Re: asl-menu

One of the gotchas with [Debian] installs is that the default search PATH does not include "/usr/sbin" ... and that's where you will find the "asl-menu" script (and others).

You can update your default path by updating the "~/.profile" file in your home directory.  As an example, I have updated my file to look like :
```
...
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# update PATH (AJN)										<--- ADDED
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"		<--- ADDED
...
```

and, yes, I should mention this in the README.  I'll add this with my next batch of changes.

**Comment by Allan-N** [comment]
Re: supermon

Q? did the actual install (step 7) fail?  or are you just not able to get the supermon page up in your browser?
Q? do you see content in the "/var/www/html/supermon/" directory?
Q? in the ASL-Install directory there is a `check-asl-services.sh` script.  What do you see when executing the script (specifically, is the Apache server running)?

**Comment by fabltd** [comment]
Its me I was expecting to see supermon2 not supermon so had the wrong URL. Panic over.

Thanks for the path above.

**Comment by fabltd** [comment]
Have you tried your script in a Docker container ? Before I give it a go?

**Comment by Allan-N** [comment]
> Have you tried your script in a Docker container ? Before I give it a go?
I have not made any efforts re: Docker containers.

FYI : one of my goals with this project was to avoid locking things down to a specific OS/build.  That's why I'm building everything from the source code.  No more dependencies on old old versions of (insert your favorite linux build).

**Comment by fabltd** [comment]
Thanks it's excellent work and was much appreciated. Not sure why the ASL project has stalled and relies on outdated OS. It's really not safe. Any reason not to use supermon2 ?

**Comment by Allan-N** [comment]
> Any reason not to use supermon2 ?
One of the gotchas I found with `Supermon2` is that the distribution did not include some of the [support] files expected by the most awesome `AllScan`.  Turns out that the missing files were installed by `Supermon`.  So, I moved from `Supermon2` back to `Supermon`.

**Comment by Allan-N** [comment]
I have updated the README.md file with comments about updating the `~/.profile` file.
