### ISSUE TITLE
Upgraded but will not boot up in new kernel

### ISSUE THREAD

**Issue by midair55** [Allan-N/ASL-Install#11]
Looking for suggestions.....  Debian Bookworm OS in use on a Raspberry Pi 3B+

The:
sudo apt update
sudo apt upgrade -y
where performed as suggested and a reboot, power cycles were performed several times.   The "asl-install.sh" continues to indicate that the kernel has changed and a reboot is needed.  Looking at the script, I see the following is compared.

$ x="/boot/vmlinuz-$(uname -r); echo $x
/boot/vmlinuz-6.1.0-rpi8-rpi-v7
$ ls -1 /boot/vmlinuz* 2>/dev/null | sort -V | tail -1
/boot/vmlinuz-6.1.0-rpi8-rpi-v8

A listing of /boot/vmlinuz returns:

/boot/vmlinuz-6.1.0-rpi7-rpi-v6
/boot/vmlinuz-6.1.0-rpi7-rpi-v7
/boot/vmlinuz-6.1.0-rpi7-rpi-v7l
/boot/vmlinuz-6.1.0-rpi7-rpi-v8
/boot/vmlinuz-6.1.0-rpi8-rpi-v6
/boot/vmlinuz-6.1.0-rpi8-rpi-v7
/boot/vmlinuz-6.1.0-rpi8-rpi-v7l
/boot/vmlinuz-6.1.0-rpi8-rpi-v8

<><><><>
Any suggestions on how to get it to boot up to 'v8' would be appreciated.

**Comment by Allan-N** [comment]
Hmmm...

I made some changes a few weeks back to "try" to catch the cases where one performed an "apt upgrade" that installed a new rev of the kernel but did not reboot their device.  In your case, it looks like a new kernel is in the /boot directory but your device is not using the latest.

I'm guessing that your "grub" configuration is, by default, selecting the older kernel.

When your system boots up are you presented with options?
Can you select the "Advanced options..."?
Are you then presented with different kernels to choose from?
and is the highlighted kernel the older version?
If so, what happens when you select the newer version?

**Comment by midair55** [comment]
I only ssh into it after a boot

**Comment by midair55** [comment]
I should clarify. I only ssh as a non-root user.  Root is ssh disabled.

**Comment by Allan-N** [comment]
So, no display / keyboard :-(

On my Debian [VM], when selecting the "Advanced options...", I can see that I have two kernels that I can choose from with the most recent version at the top of the list.  It also looks like all of the details are in "/boot/grub/grub.cfg".  Reading, online, it looks like the `sudo /usr/sbin/update-grub` will update this file.

I've got a couple of suggestions for you but please don't hold me responsible should anything break (I have no expertise here) ...

1. exec `sudo grep vmlinuz /boot/grub/grub.cfg` to view what kernel choices are known to grub and their ordering
2. if the older kernel is listed first then exec `sudo update-grub` and then check the order again
3. check the "/etc/default/grub" file for a GRUB_DEFAULT setting.  If other than blank or "0" then you will likely need to use `sudo grub-set-default 0` to clear that value
4. reboot (with fingers crossed)

and if that doesn't help then you might try removing the older vmlinuz kernel file, again run `sudo update-grub`, and reboot (with both fingers and toes crossed).

**Comment by midair55** [comment]
Thank you Sir!!!   I’ll give it a shot.   No warranty implied. I have
several SD cards to burn….

I’m sorta familiar with Linux and the ”shell” having cut my teeth on UNIX
in ‘85 working at Bell Labs.  Goodness things have changed!!   I thought I
was in heaven when the Korn Shell came out and you could call up your
‘history’ and edit previously entered commands….

**Comment by midair55** [comment]
grub is not installed.  A quick search suggests it is unsupported on a Raspberry Pi.

Another 'upgrade' was performed with the following results:

sudo apt upgrade -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  linux-headers-6.1.0-rpi7-common-rpi linux-headers-6.1.0-rpi7-rpi-v6
  linux-headers-6.1.0-rpi7-rpi-v7 linux-headers-6.1.0-rpi7-rpi-v7l
  linux-image-6.1.0-rpi7-rpi-v6 linux-image-6.1.0-rpi7-rpi-v7
  linux-image-6.1.0-rpi7-rpi-v7l linux-image-6.1.0-rpi7-rpi-v8:arm64
Use 'sudo apt autoremove' to remove them.
The following packages have been kept back:
  linux-image-rpi-v8:arm64
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
<><><><>

The autoremove was executed as suggested by the upgrade output.

asl-install.sh continues to indicate that a boot is needed.

uname -r - returns "6.6.20+rpt-rpi-v7"

The issue is being closed.



It appears that although

**Comment by Allan-N** [comment]
Thank you for the feedback.  I'm going to update the README to suggest exec'ing `sudo apt autoremove` after the upgrade.
