### ISSUE TITLE
Fast Busy?

### ISSUE THREAD

**Issue by KenHorse** [Allan-N/ASL-Install#12]
Installed on fresh Debian 12 install. All went without error but when I transfer my /etc/asterisk files from an existing Debian11 installation (which is a radioless hub for 3 other ASL nodes and works fine under 11) and restart the node, a fast busy signal is sent to all connected nodes.

**Comment by Allan-N** [comment]
While I don't have lots of experience troubleshooting connectivity issues I can certainly ask a bunch of questions that will hopefully guide you to an answer.

- In the "ASL-Install" directory you should find a "check-asl-services.sh" script.  You can exec the following command to see that all of the services are up/running :
```
sudo ./check-asl-services.sh
```
and, yes, it's OK if the DAHDI status is "active (running)"
- You can exec the following command to check if your node(s) show up as registered :
```
sudo asterisk -rx "iax2 show registry"
```
- To confirm, you don't have two radioless hubs running at the same time, each trying to register the same nodes, correct?
- Does your new Debian 12 hub have the expected local IP address?
- Do you have the port forwarding rules setup to correctly forward traffic to the [Debian 12]'s IP address?
- Are you having issues connecting FROM the Debian 12 hub nodes to other/internet ASL nodes?  or are you having issues connecting from other/internet nodes TO the Debian 12 hub nodes?
- Any firewalls or VPNs in your configuration?  If so, please check the configurations.

I hope the above helps.

**Comment by KenHorse** [comment]
Yes, same IP, same rpt.conf, same everything except for Debian 12 and your build. I don't understand why (or where for that matter) the fast busy is being generated and sent to all connected nodes. Once again, I took all my config files (/etc/asterisk) from a 100% working Debian11 installation and moved them to the Debian12 version. I might mention this is a guest running under Proxmox. It is also worth noting I am not a newbie with ASL - I totally know all the usual steps to get a node up and running nodes (these are all private nodes by the way). They all connect to the Deb12 hub just fine.

Let me add, I'm using Debian 12.4.0 amd64

**Comment by Allan-N** [comment]
Hmmm...  One other thing to check would be the /etc/asterisk/* configuration file ownership/permissions (and I'm asking because you said that you transferred files).  Beyond that, I'll have to dig around for more ideas.

... and, to clarify, where/when/how are you seeing the fast busy signals?  Is this incoming to the hub?  outgoing from the hub?  ...?  Are there any messages in the asterisk logs?

**Comment by KenHorse** [comment]
The logs aren't particularly helpful and don't show anything unique

When the problem happens, it apparently is generated in the hub node itself and sent to all connected nodes. So they all transmit the fast busy to their respective repeaters. 

However, I have tracked down the cause of this (mis)behavior - I run a 2nd node (that is public) on the same server as the hub node. I also have a startup macro defined to connect to this public node, as well as the other private nodes in my system (a total of 5). If I remove this 2nd node from the startup macro, everything is good (with no fast busy). If I manually connect to this 2nd node, the fast busy starts again (it takes about 5 seconds or so). 

Again, this did not happen under Debian11, running F4HWD's build (https://github.com/F4HWD/ASL-Asterisk). Maybe that will help track down the cause of the issue

**Comment by Allan-N** [comment]
Thank you for the added info.  I took a very quick look at F4HWD's fork.  The GitHub code page says :
```
This branch is 13 commits ahead of, 126 commits behind AllStarLink/ASL-Asterisk:develop.
```
That's a bunch of changes!  I will certainly "look" but make no promises that I will see "the change" that would explain the errant behavior.

**Comment by KenHorse** [comment]
I found the problem  - totally unexpected. 

Remember I said I had 2 nodes on that one server? Well, the 2nd node stanza contained a line that defines the startup macro (startup_macro=*5100) but so does the 1st node stanza. Apparently that caused an error as that 2nd call to startup_macro=*5100 ran. I removed it from the 2nd node stanza and all is good again. 

I guess the Debian11 build didn't quite catch that error?

**Comment by Allan-N** [comment]
Excellent that you found the issue.

... and, yes, one would hope that software would be more informative about how issues are reported.  No, we don't want to flood the logs with noise but we also don't want to be silent.

Enjoy ASL running on Debian 12!
