### ISSUE TITLE
Registration?

### ISSUE THREAD

**Issue by KenHorse** [Allan-N/ASL-Install#13]
I've taken my working config files from Deb11 and moved them to the new Deb12 installation. Now, neither ASL nor Echolink is registering with their respective servers. ASL itself is working (this installation is part of a private ASL network and they connect and talk fine with each other)

**Comment by Allan-N** [comment]
Q? did you also report this issue to the AllStarLink Community?

And, to confirm, are you still comparing the behavior from your Deb11 install that was based off of the F4HWD build?  If so, and I had commented about this in an earlier issue that you reported (#12), the F4HWD fork shows the following :
```
This branch is 13 commits ahead of, 126 commits behind AllStarLink/ASL-Asterisk:develop.
```
That's a bunch of change and it's possible that (a) the F4HWD fork included some fixes that are not in the ASL build, (b) the ASL repo had some fixes that don't align with the configuration files that you had been using on the Deb11 system, (c) a combination of these two, or (d) something else is off.

I am most certainly not an expert in Asterisk/AllStar configurations (the folks on the community forum would likely be able to help our more) but I'm happy to look at what you've got.

**Comment by KenHorse** [comment]
Yup, I sure did. No replies as of yet (posted yesterday)

Also yes to F4HWD build. 

What I have been able to determine (so far) is that the ASL stats server doesn't like the data being thrown it and is returning an Error 422. A bit more snooping has shown that the wrong node # is being sent to the stat server (I run both a private node 1100 and a public node 57387 on my Debian 12 ASL server). For some reason, your build is sending the wrong node # even though I have the correct one specified in iax.conf.

**Comment by Allan-N** [comment]
AFAIK, the ASL stats reflect whether you have "statpost_url" lines in your rpt.conf file.  If commented out, there would be no posting.  If present, the stats should be posted to the specified URL (http://stats.allstarlink.org/uhandler.php) ... for the node where the statpost_url line(s) are in the conf file

**Comment by Allan-N** [comment]
FYI, it does look like node 57387 has "registered" with ASL.
```
# host -t TXT 57387.nodes.allstarlink.org
57387.nodes.allstarlink.org descriptive text "NN=57387" "RT=2024-04-07 22:03:55" "RB=0" "IP=204.195.101.147" "PIP=0" "PT=4569" "RH=register-west"
```
so maybe your issue is just "stats".  I would most certainly review the "statpost_url" line(s) in your rpt.conf file.

**Comment by KenHorse** [comment]
That is my understanding as well. It wasn't commented out in the Deb11 version either and it worked there (as I mentioned). 

Yes, it registered because I manually ran wget http://stats.allstarlink.org/uhandler.php?node=57387&time=1712432633&seqno=21&nodes=T1101,T57387,T1002,T1103,T1102&apprptvers=2.0.0&apprptuptime=205&totalkerchunks=0&totalkeyups=0&totaltxtime=0&timeouts=0&totalexecdcommands=6

For some reason, your code is using node # 1100 and not 57387 and that appears to be the problem (1100 is a private node and their server doesn't know about it)

**Comment by Allan-N** [comment]
I "thought" that the IAX and statpost registrations were separate (one from iax.conf and the other from rpt.conf).

**Comment by KenHorse** [comment]
All I can say is that I noticed if it doesn't like the stats, nothing is shown from that node. I'm also noticing that Echolink isn't registering either

**Comment by Allan-N** [comment]
After you shutdown/restart the node ... and do not run the "wget" ... can you check if it is accessible/known by (a) trying to connect from another node and (b) look at the DNS "TXT" record.  If these return positive results then we will know that the "node" has been registered.  Then, you can go to the stats page.  If missing then your issue is with the statpost.

Also, did you use the node-setup command/menu on your Deb12 system?  and did you make any changes?  Asking here because there could be an issue with making changes to a config with multiple nodes.

**Comment by KenHorse** [comment]
Currently, the statpost_url lines are commented out in my rpt.conf file. Restarted the node and still no go. 

No, I didn't run the setup script - I copied all files from /etc/asterisk on Deb 11 over this one. Perhaps there's a change somewhere along the line in one of the conf files?

**Comment by KenHorse** [comment]
The asl-menu setup doesn't allow multiple node definitions, FYI

**Comment by KenHorse** [comment]
Just to clarify, I restarted the node and didn't run wget. Outside nodes cannot connect to 57387 nor does it show in the registry. So I guess the stats server issue isn't the only one

**Comment by KenHorse** [comment]
Are you getting my emails? I'm not sure they're making it

**Comment by Allan-N** [comment]
Haven't seen any e-mail messages.

Did you get the one that I sent you?

**Comment by KenHorse** [comment]
I did. I've had problems with my domain to mac.com before...What I sent was:

Hi Allan

Yea, probably best to move this off Github for now.

I am absolutely positive it isn't a port forwarding or other network issue and I based that on the fact that both the Debian11 instance and Debian12 one are actually Proxmox guests (VMs), with the exact same MAC address, which is reserved in my router. And yes, I am sure only one is running at a time <g>. 

I commented out the statpost_url lines because /var/log/asterisk/messages was showing line after line of the following:

ERROR[588] app_rpt.c: statpost to URL <http://stats.allstarlink.org/uhandler.php?node=1100&time=1712440302&seqno=2&keyed=0&keytime=10> failed with code 422

Note it trying to send info on Node # 1100, even though my iax.conf says:

register=57387:mypassword@register.allstarlink.org 

If I could figure out where it getting the "1100" to use with the statpost_url line, I could probably fix this. But I've grep'd every which way I can think of and I haven't yet found it

Oh and:

root@ButtevilleASL:~# host -t TXT 57387.nodes.allstarlink.org

57387.nodes.allstarlink.org descriptive text "NN=57387" "RT=2024-04-07 23:06:01" "RB=0" "IP=204.195.101.147" "PIP=0" "PT=4569" "RH=register-west"

**Comment by Allan-N** [comment]
We have now exchanged e-mails.

... and to those following GitHub, we will try to share our findings.

**Comment by Allan-N** [comment]
After a few back-n-forth e-mails I received the following from Ken :

> I've narrowed down the problem. 
> 
> As you might remember, I am running 2 nodes on 1 ASL server. Through trial and error, I determined that I was missing some definitions from the public node. I guess the Deb11 version of ASL didn't care. 
> 
> Anyway, I'm up and running now with your build and full registrations and connectivity
>
