### ISSUE TITLE
asl-install.sh

### ISSUE THREAD

**Issue by du6jip** [Allan-N/ASL-Install#15]
Problems installing

./asl-install.sh: line 97: whiptail: command not found

Thanks

**Comment by du6jip** [comment]
Got it working using Oracle, but having problems with firewall.

**Comment by Allan-N** [comment]
> Got it working using Oracle

Nice!

> but having problems with firewall.

The install script doesn't touch the network configuration.  If your OS has a firewall enabled then it would be up to you to ensure the needed ports are open and/or forwarded.

But, please feel free to provide more details on what you have and what's not working.

**Comment by du6jip** [comment]
Sorry if I made your expect I installed it using Oracle Linux. I installed it on Ubuntu 22.04. It is working now, I have to update the iptables. Oracle is different. 
I dont know why when I tried this on AWS Ubuntu 22.04 all I did was add security ingress for Allstar and supermon and right away I can access the server.
Oh with regards to Supermon, you fork this from HAMVOIP? astdb .php is not working on. It is updating but I think HAMVOIP saves it on a different folder and supermon does not sees the astdb.txt and all the nodes appears as private.
Can this repo be install on ARM64 cpu. on Oracle I am still using AMD64. This would be excellent if this would and DAHDI will not crap out. ARM64 is not supported with DAHDI as far as I remember. I was afraid it will be the same as the last time that I used Ampere, which is nice and is also a free tier and nice specs.
Thanks for your work
73
KC1JFN

**Comment by Allan-N** [comment]
> Oh with regards to Supermon, you fork this from HAMVOIP?

No, I forked from ASL-Supermon. I know there are "newer" versions out there but I have not found a source repo. 

> Can this repo be install on ARM64 cpu. on Oracle I am still using AMD64. 

I have never tried building for Oracle. If all is "close" to Debian then maybe. Else, your success may depend on how much effort you want to put in.

**Comment by du6jip** [comment]
Oh ok, I just thought it was from HAMVOIP since if you run ./astdb.php the
result was in /var/log/asterisk, while ASL supermon's result is in
/var/www/html/supermon. The CPU temp and weather is blank. Also ASL version
that I know of start with version 7

But anyway, I am glad that there is a repo that works on Debian 12, ubuntu
22.04

Thanks for your hard work.

73

**Comment by Allan-N** [comment]
So, given the back-in-forth, are there any issues that I need to look at for this install script?

**Comment by du6jip** [comment]
The install script was flowless, perfect, its just if you can change the
supermon to ASL version. I know you told me you fork it from ASL and not
HAMVOIP but like the astdb.php, if you run it, it appends the astdb.txt to
/var/log/asterisk just like in HAMVOIP, while ASL version puts it on
/var/www/html/supermon.

I forgot to tell you that I installed dvswitch-server with it. And I works
perfectly with the dasboard


As you can see on the supermon the weather data is missing, cause I think
HAMVOIP pionts it on a different path not where ASL server runs the weather
script.

Quirky little things but overall Im very satisfied with it.

Thanks and 73

KC1JFN

**Comment by Allan-N** [comment]
- I'll take a look at the astdb.php handling.
- I'll take a look at the Supermon / weather config
- dvswitch-server ... good to know

**Comment by du6jip** [comment]
Hi, Allan there isone thing that need to be addressed. I was looking how to install supermon 7.4+ and when I login on putty there is a message that a new upgrade is ready to install. I said oh no DAHDi doesnt like new a kernel. After restarting it, allstar is running anymore. I had to reinstall from the start. This time I uninstall unattended-upgrade service and put a hold on kernel upgrades.  I hope this will work. Both AWS and Oracle pushed a new Kernel upgrade. I was trying to update the supermon with the one found on group.io supermon ASL.
https://groups.io/g/Supermon/topic/83794098?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3ACreated%2C%2C%23Update-Announcement-2%2C20%2C2%2C0%2C83794098%2Cct%253D1&ct=1

**Comment by Allan-N** [comment]
>> The install script was flowless, perfect, its just if you can change the
> supermon to ASL version. I know you told me you fork it from ASL and not
> HAMVOIP but like the astdb.php, if you run it, it appends the astdb.txt to
> /var/log/asterisk just like in HAMVOIP, while ASL version puts it on
> /var/www/html/supermon.
>
> I'll take a look at the astdb.php handling.

So, I've looked at both the AllStarLink/ASL-Asterisk and AllStarLink/ASL-Supermon projects I am pulling code from and all of the references are to `/var/log/asterisk/astdb.txt`.  Unless something is not working with THESE packages then I'm not going to stir the pot with random changes to match up with X, Y, or Z.

**Comment by Allan-N** [comment]
> > As you can see on the supermon the weather data is missing, cause I think
> HAMVOIP pionts it on a different path not where ASL server runs the weather
> script.
>
> I'll take a look at the Supermon / weather config

Well, here things get a bit messy.  The AllStarLink/ASL-Supermon source includes references to `get_temp` and `weather.sh`.

The former is a shell script included in the [ASL-Supermon] sources that looks at some OS (and device) specific state.  This might (or might not) on your system.

For the latter, all I can find is where the Supermon web page exec's the script.  As for the actual script, this looks to have been provided by some other software package (e.g. the "newer" version of Supermon that I have not been able to find in source form).

**Comment by Allan-N** [comment]
No more discussion, closing.
