### ISSUE TITLE
asl-install.sh fails with obsolete macros when using WSL-2 Debian

### ISSUE THREAD

**Issue by nswartz99** [Allan-N/ASL-Install#16]
This should help improve the scripts:

AC_SUBST, AC_HELP_TOOLS, others are obsolete so the script fails. 
You need to run autoupdate on the configure files.

At line 481 I changed:
 (cd ASL-DAHDI/tools;        autoupdate ;  autoupdate acinclude.m4;             autoreconf --install --force) 

Secondary issue:
I am trying to install for Debian under Windows WSL-2 and there are no kernel sources. You need to install linux-headers-generic and create symbolic links for /lib/modules/5.15.146.1-microsoft-standard-WSL2.
You also need to do
sudo bash -c "echo '[1] [00049] [~~  ] [runlevel] [~           ] [4.4.0-17115-Micoroso] [0.0.0.0        ] [$(date)]' | utmpdump -r >/var/run/utmp"
and then sudo su - <username>
to run commands. This is all so that the "who" command works.

Unfortunately, the end result is that it wants the actual URI hardware and I do not have that.

**Comment by nswartz99** [comment]
Also, later:
(cd ASL-Asterisk/asterisk;  autoupdate;     autoupdate menuselect/configure.ac menuselect/acinclude.m4 autoconf/*.m4;       autoreconf --install --force)

**Comment by Allan-N** [comment]
I am happy to look at your suggested "autoupdate" changes.  As long as they don't break the platforms I've already tested then I'll drop them in.

As for Windows WSL-2, is there a good web site that talks about installing/using WSL-2 (so that I can repro)?

**Comment by nswartz99** [comment]
I am still trying to get it to run. I managed to get it to build completely, but it does not start. Checking into that.

I will write up notes on how I did it and send you that.

I have not found anyone else documenting how to use ASL under WSL. I am supporting our club repeater that is using a Raspberry Pi, but I wanted to be able to test things using my PC and rig with a Digimode cable.

 

Maybe you could answer a question. At one point the build had an error: “No Hardware Found” because the USB.pm did not contain the model info for the cable I use. 

I added:

'0d8c:0012'     => { DRIVER => 'wcusb', DESCRIPTION => 'Digimode' },

 

I am not sure this is right. The DMK URI has the same model number. Do you know what driver would be best for this?

**Comment by Allan-N** [comment]
> I am still trying to get it to run. I managed to get it to build completely, but it does not start. Checking into that.

OK

> I will write up notes on how I did it and send you that.

That would be great

> I have not found anyone else documenting how to use ASL under WSL. I am supporting our club repeater that is using a Raspberry Pi, but I wanted to be able to test things using my PC and rig with a Digimode cable.

Honestly, until you had filed this issue I had not heard of  Windows WSL.  Also, I try very hard to avoid Windows :-)

> Maybe you could answer a question. At one point the build had an error: “No Hardware Found” because the USB.pm did not contain the model info for the cable I use.
> 
> I added:
> 
> '0d8c:0012'     => { DRIVER => 'wcusb', DESCRIPTION => 'Digimode' },
> 
> I am not sure this is right. The DMK URI has the same model number. Do you know what driver would be best for this?

If the VendorId/ProductID is '0d8c:0012' then you likely have a device with a CM108B.  But, that would be the extend of my knowledge.

I am going to keep this issue around to address [just] the autoupdate / autoconfig change.

... and it would be good to create a new issue for any needed Windows WSL changes (if you can get it working)

**Comment by nswartz99** [comment]
Thanks for the response. I got stuck using WSL. Apparently it does not directly support audio. It uses PulseAudio which is a redirector thingy. I don't think that is going to work. I don't think any specific changes are needed to support WSL if they every implement direct audio drivers. I will only open an issue for this if I see changes needed to your repo.

**Comment by Allan-N** [comment]
Thank you for the WSL update.  I'm sure that many are watching for audio support updates.
