### ISSUE TITLE
Install this on local server help

### ISSUE THREAD

**Issue by wrhowell** [Allan-N/ASL-Install#17]
Is it possible to walk thru installing this on a home server that has a radio attached to it. I've got it installed without issues, just can't get it to communicate with the RIM-Maxtrac-RM interface assemble between radio and server. I'm wondering if I have to add something to dial group or make a group fro allstar or what.

Any help would be greatly appreciated. Sure would make an allstar install doing it your way a much easier way of doing things.

Thank you,

William, KI5PHN

**Comment by Allan-N** [comment]
Does `lsusb` show the RIM-Maxtrac-RM interface?

If so, you shouldn't have to do much more than configuring the "Radio Interface" as "SimpleUSB" and using the "Interface Tune CLI" to select the USB device.

As for a walk thru, I think you'd get more/better help from the Community forum or other mailing lists.

**Comment by Allan-N** [comment]
All quiet here.  Closing.

**Comment by Allan-N** [comment]
All quiet here. Closing.
