### ISSUE TITLE
DAHDI DUMMY and hold kernel

### ISSUE THREAD

**Issue by froggy0077** [Allan-N/ASL-Install#18]
Hi Allan-N,
 Great work on your ASL build for Debian 12 Bookworm. I have just setup a node on AMD64 -DELL WYSE thin client one suggestion is you load DAHDI DUMMY module to your installer script to give the required timing when using a USB audio devices.
In the ASL-DAHDI
sudo make
sudo make install
sudo apt autoremove
sudo apt autoclean
sudo su
echo -e "#needed for rpi timing \ndahdi_dummy" >>/etc/modules
modprobe dahdi_dummy
exit
And Hold the Kernel
sudo apt-mark hold linux-image-$(uname -r)

**Comment by Allan-N** [comment]
> one suggestion is you load DAHDI DUMMY module to your installer script to give the required timing when using a USB audio devices

I will look into this.

> And Hold the Kernel

I've thought about this issue and (to me) I think I want to do more than just hold the kernel.  What I'm thinking about is having the "Setup" action remove any holds, apt update, apt upgrade, and then re-apply any holds.  Just need time to put the pieces together and do a bunch of testing.
