### ISSUE TITLE
compile error on Debian 12 aarch64

### ISSUE THREAD

**Issue by pcpackrat** [Allan-N/ASL-Install#2]
cc1: error: unknown value ‘aarch64’ for ‘-march’
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8.7-a armv8.8-a armv8-r armv9-a native
Assembler messages:
Error: unknown architecture `aarch64'

Error: unrecognized option -march=aarch64

Is it possible to compile this on aarch64?

**Comment by Allan-N** [comment]
> Is it possible to compile this on aarch64?
I don't know.  The only platforms that I've built (so far) have been x86 (x86_64, amd64).

What device are you trying to build on?

Also, are you getting these errors from the DAHDI build?  the AllStarLink build?  ...?

Lastly, the full build logs should be available in the /var/tmp directory.

**Comment by pcpackrat** [comment]
Remarkably, DAHDI compiled.  That’s always been my brick wall.

Building on a Pi4 with Debian 12.4

***@***.***:~/ASL-Install# uname -a
Linux tacotruck 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux


It barks at aarch64 for the proc so I hacked up the makefiles and changed it to native.  Things progress and then choke on the gsm codec.

I attached the build logs.

The build-asterisk.txt is after a clean pull.

The “afteredits” log was after I changed the makefiles –march= settings to native instead of $PROC.  This may just be a trip down futility lane.

I have heard others have compiled the ASL 2.0 beta successfully on a pi4.   Probably an older OS though.

-Michael

**Comment by pcpackrat** [comment]
Same error with the github.com/AllStarLink/ASL-Asterisk/ source. Assuming they are the same.

**Comment by Allan-N** [comment]
I will put this issue on my "to investigate" list.  Fortunately, I have a spare RPi 4.  Just need a bit of time :-)

**Comment by Allan-N** [comment]
> Same error with the github.com/AllStarLink/ASL-Asterisk/ source. Assuming they are the same.
Essentially, yes.  My fork has a few minor changes for building/installing on recent Amazon Linux [2023] and Debian [12] systems.  Check out the commit history for the specifics.

**Comment by Allan-N** [comment]
Just to make sure, are you starting with a Debian image from https://raspi.debian.net ?

**Comment by pcpackrat** [comment]
I used the Raspberry Pi Imager and chose the minimal in other.

**Comment by Allan-N** [comment]
Raspberry Pi OS Lite (64-bit) ?

**Comment by Allan-N** [comment]
Just to let you know, I have reproduced the build failure.  Now, to see if I can figure out "why" and identify a fix :-)

**Comment by pcpackrat** [comment]
I appreciate the effort.  I enjoy puzzles I have a clue on and this is not where my skills are.

-Michael

**Comment by Allan-N** [comment]
Problem found and fixed ... with the changes in my GitHub fork of the ASL-Asterisk project.

What you will need to do is :

```
cd <directory where you cloned my ASL-Install project>
./asl-install.sh
```
 
and then start from the top with "1. Setup", ...

**Comment by pcpackrat** [comment]
Thanks for fixing it.

-Michael

On Dec 27, 2023 19:50, Allan Nathanson ***@***.***> wrote:

Problem found and fixed ... with the changes in my GitHub fork of the ASL-Asterisk project.

What you will need to do is :

cd
./asl-install.sh

and then start from the top with "1. Setup", ...

**Comment by pcpackrat** [comment]
It compiled.  

Looks good.  BTW, there is a typo on line 51 and 56? in the asl-install.sh for the Terminal settings.  Trivial but there.

**Comment by Allan-N** [comment]
Typo's fixed :-)
