### ISSUE TITLE
chown: cannot access '/dev/dahdi': No such file or directory

### ISSUE THREAD

**Issue by michalsiman** [Allan-N/ASL-Install#21]
Installing DAHDI than:

```
Build/install DAHDI
* autoupdate (configure.ac)
* autoupdate (acinclude.m4)
* autoreconf
* make
* make install
* make config
* make tools/install-config
chown: cannot access '/dev/dahdi': No such file or directory
chmod: cannot access '/dev/dahdi': No such file or directory
Build/install Asterisk
```

No DAHDI installed on the system. It is fresh UBUNTU 22.04 with all update/upgrade on beginning. Running on Dell Wyse 3040. Fresh Ubuntu server image from today.

**Comment by Allan-N** [comment]
Do you have "Secure Boot: Disabled" on your Dell Wyse 3040?

You might also try rebooting your system and restarting ./asl-install from the "Build/install Asterisk" step.

**Comment by michalsiman** [comment]
Thank you Allan, i have for sure enable secure boot, i will try it tomorrow
disable and continue install. Thx. Just idea: cannot be this controlled by
script before start installation?

Michal Siman
(OK1SIM)



čt 30. 5. 2024 v 14:28 odesílatel Allan Nathanson ***@***.***>
napsal:

**Comment by Allan-N** [comment]
> Just idea: cannot be this controlled by script before start installation?

Can I change the "Secure Boot" setting from the installation script?  I don't think this is possible but if you know a way then please share.

Do I know a way to check if secure boot is enabled/disabled?  I do not ... but if you know how then please share.

Is it possible to build/compile DAHDI such that it could be used on a system with "Secure Boot" enabled?  Possibly, but I have not been thinking about going down that path.  What I have is working :-)

**Comment by michalsiman** [comment]
Just idea, i dont know if it is possible or no, i am not a linux specialist
as you can see.

Founded just this, dont know if this can help in real situation like i have
.... i can try and see output with and without secureboot enabled ...
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/verify-uefi-secure-boot.html

Michal Siman
(OK1SIM)



čt 30. 5. 2024 v 20:46 odesílatel Allan Nathanson ***@***.***>
napsal:

**Comment by Allan-N** [comment]
Interesting.  I exec'd the `mokutil --sb-state` command on my 3040 and got back "SecureBoot disabled".  If the command is available on your system and it returns something like "SecureBoot enabled" then I could have the script check the result and issue a warning.  Please let me know what your system currently returns.

**Comment by michalsiman** [comment]
My mokutil answer on my current system with secureboot enable:

***@***.***:~$ mokutil --sb-state
SecureBoot enabled

and when i disable secureboot in bios and restart for sure than:

***@***.***:~$ mokutil --sb-state
SecureBoot disabled

Looks like working solution (on Ubuntu 22.04).



Michal Siman
(OK1SIM)



čt 30. 5. 2024 v 22:29 odesílatel Allan Nathanson ***@***.***>
napsal:

**Comment by michalsiman** [comment]
Just btw, final result, disable secureboot in bios help me with my problem
in Ubuntu 22.04 - now i have working installation of ASL on Dell Wyse 3040.

Thx for the script Allan - good work!

Michal Siman
(OK1SIM)



pá 31. 5. 2024 v 9:38 odesílatel ***@***.***> napsal:

**Comment by Allan-N** [comment]
Thank you for sharing the output from the `mokutil` command.  I will add a check to the install script.
