### ISSUE TITLE
No /dev/dahdi installed

### ISSUE THREAD

**Issue by N6GKJ** [Allan-N/ASL-Install#4]
I have installed this software two times. The first time it I thought maybe the install was corrupted. I re-installed Linux Mint 21 and installed ASL-Install a second time. Still no /dev/dahdi. I copied /dev/dahdi from a Raspberry Pi running hamvoip and placed it into the /dev directory. Issue solved. Maybe there is  step missing to install /dev/dahdi in the build or install process??

**Comment by Allan-N** [comment]
Danger... pulling code from one OS and dropping it on another, especially kernel code, is likely gonna get you in trouble.

**Comment by Allan-N** [comment]
FYI : I just installed LinuxMint in a VM and exec'd the latest version of the project.  I didn't have any issues with `asl-install`.

Note: one recent observation I've had relates to an "apt upgrade" bumping the kernel version and folks (including myself) not rebooting before trying an install.  The end result was having DAHDI build with "old" headers.  Rebooting, re-exec'ing the script, and re-building all has been the ticket.
