### ISSUE TITLE
Feature Request - MOTD with IP / HostName

### ISSUE THREAD

**Issue by fabltd** [Allan-N/ASL-Install#6]
The office ASL Images create a MOTD that displays the host name and the IP address of the server.

Is this somthing that can be added to the build script?

**Comment by Allan-N** [comment]
What ASL Images have this functionality?

Note : my focus has been on installing/running a working AllStar node on a system/device that's running recent OS builds ... and making that a relatively painless process. I have been thinking about adding support for other ASL related components (e.g. Echolink, Allmon, etc).  What I'm not interested in are the system administration details (e.g. hostnames, networking, shell prompts, MOTD, etc).  I'm also not going down the path of creating an installable image that's ready to go.

**Comment by fabltd** [comment]
Hi - Its in the V2 Images.

**Comment by Allan-N** [comment]
Link (or command one would use to fetch those images) ?

**Comment by fabltd** [comment]
http://downloads.allstarlink.org/index.php?b=ASL_Images_Beta

**Comment by Allan-N** [comment]
As I wrote earlier, I am not interested in [re-]creating a full OS image with every little extra that folks might want. 

But, I did find out a bit more about how the ASL V2 OS image is updating the /etc/motd file.  The changes appear to be driven by some extras added by the AllStarLink / ASL-Live-Build GitHub project.

Specifically, there's the shell script that updates the file :
  https://github.com/AllStarLink/ASL-Live-Build/blob/develop/config/includes.chroot/usr/local/sbin/update-motd-issue.sh
... and then there are a few places where that script looks to be executed (e.g. network up, a periodic cron job)

Your system is yours to customize as you please.  This is just not something for my ASL-install project.
