### ISSUE TITLE
Trouble getting Asterisk to run on Pi Bookworm

### ISSUE THREAD

**Issue by hwdornbush** [Allan-N/ASL-Install#8]
I am having trouble getting Asterisk to run. My environment is Pi 4 with Bookworm downloaded and nothing else done in it before downloading and running asl-install.sh. Is saw no error messages when running the script. Here is the output from check-asl-services.sh:

● dahdi.service - LSB: DAHDI kernel modules
Loaded: loaded (/etc/init.d/dahdi; generated)
Active: active (exited) since Sun 2024-02-18 14:27:00 EST; 26min ago
Docs: man:systemd-sysv-generator(8)
Process: 1176 ExecStart=/etc/init.d/dahdi start (code=exited, status=0/SUCCESS)
CPU: 27ms

Feb 18 14:27:00 localhost.localdomain systemd[1]: Starting dahdi.service - LSB: DAHDI kernel modules...
Feb 18 14:27:00 localhost.localdomain dahdi[1176]: No DAHDI modules on the system. Not starting
Feb 18 14:27:00 localhost.localdomain systemd[1]: Started dahdi.service - LSB: DAHDI kernel modules.
○ asterisk.service - Asterisk PBX and telephony daemon
Loaded: loaded (/lib/systemd/system/asterisk.service; enabled; preset: enabled)
Active: inactive (dead)
Docs: man:asterisk(8)

Feb 18 14:28:34 localhost.localdomain systemd[1]: Dependency failed for asterisk.service - Asterisk PBX and telephony d>
Feb 18 14:28:34 localhost.localdomain systemd[1]: asterisk.service: Job asterisk.service/start failed with result 'depe>
lines 1-7/7 (END)

I don't really know what to look for in the log files. In looking at /var/tmp/build-asterisk. There were lots of yes and no. The only thing that jumped out at me was:

checking for pkg-config... pkg-config
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk+-2.0', required by 'virtual:world', not found
configure: creating ./config.status
config.status: creating makeopts
config.status: creating autoconfig.h
configure: configuring in mxml
configure: running /bin/bash './configure' --prefix=/usr/local --cache-file=/dev/null --srcdir=.

Since I am new at both ASL and Linux, I am not sure where to go from here.

**Comment by Allan-N** [comment]
First off, thank you for creating a new issue.  Trying to juggle multiple conversations and possibly different issues in one place is not fun.

First off, I would like to know how you created your initial RPi4 image.  Did you use the Raspberry Pi Imager application?  and what specific operating system / options did you choose (64-bit, 32-bit, with the desktop, Lite, etc)?

Q? did you reboot your RPi after you completed all of the installation steps before exec'ing "sudo ./check-asl-services.sh"?  If not, a reboot is quick/easy.

You mentioned looking at the build-asterisk.txt file with nothing jumping out.  Did you also look at the /var/tmp/build-dahdi.txt file?  In these files, I tend to look for the word "error" and also whatever text is near the end of the file.  Sometimes an error jumps right out, other times you only see how the various compilation/linking/install steps progressed.

**Comment by hwdornbush** [comment]
I used the Raspberry Pi imager and chose Raspberry Pi OS 64-bit, 2023-12-05.  I could have chosen something else but your posting only said Bookworm so I chose the "recommended" version.

I rebooted my Pi several times to see if it would make any difference, and it did not.  "sudo ./check-asl-services.sh" was executed after a reboot.  I just reran it and got:

root@myaa6bd:/home/pi/ASL-Install# ./check-asl-services.sh
● dahdi.service - LSB: DAHDI kernel modules
     Loaded: loaded (/etc/init.d/dahdi; generated)
     Active: active (exited) since Sun 2024-02-18 15:05:52 EST; 18h ago
       Docs: man:systemd-sysv-generator(8)
    Process: 1168 ExecStart=/etc/init.d/dahdi start (code=exited, status=0/SUCCESS)
        CPU: 27ms

Feb 18 15:05:52 myaa6bd systemd[1]: Starting dahdi.service - LSB: DAHDI kernel modules...
Feb 18 15:05:52 myaa6bd dahdi[1168]: No DAHDI modules on the system. Not starting
Feb 18 15:05:52 myaa6bd systemd[1]: Started dahdi.service - LSB: DAHDI kernel modules.
○ asterisk.service - Asterisk PBX and telephony daemon
     Loaded: loaded (/lib/systemd/system/asterisk.service; enabled; preset: enabled)
     Active: inactive (dead)
       Docs: man:asterisk(8)

Feb 19 09:36:03 myaa6bd systemd[1]: Dependency failed for asterisk.service - Asterisk PBX and telephony daemon.
Feb 19 09:36:03 myaa6bd systemd[1]: asterisk.service: Job asterisk.service/start failed with result 'dependency'.
● update-node-list.service - AllStar NodeList Diff Updater
     Loaded: loaded (/lib/systemd/system/update-node-list.service; enabled; preset: enabled)
     Active: active (running) since Mon 2024-02-19 09:36:03 EST; 10min ago
   Main PID: 2030 (update-node-lis)
      Tasks: 2 (limit: 8734)
        CPU: 1.077s
     CGroup: /system.slice/update-node-list.service
             ├─2030 /bin/bash /usr/sbin/update-node-list.sh
             └─2341 sleep 60

Feb 19 09:36:03 myaa6bd systemd[1]: Started update-node-list.service - AllStar NodeList Diff Updater.
● apache2.service - The Apache HTTP Server
     Loaded: loaded (/lib/systemd/system/apache2.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-02-18 15:05:46 EST; 18h ago
       Docs: https://httpd.apache.org/docs/2.4/
    Process: 762 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
   Main PID: 875 (apache2)
      Tasks: 6 (limit: 8734)
        CPU: 268ms
     CGroup: /system.slice/apache2.service
             ├─875 /usr/sbin/apache2 -k start
             ├─896 /usr/sbin/apache2 -k start
             ├─897 /usr/sbin/apache2 -k start
             ├─898 /usr/sbin/apache2 -k start
             ├─899 /usr/sbin/apache2 -k start
             └─900 /usr/sbin/apache2 -k start

Feb 18 15:05:45 myaa6bd systemd[1]: Starting apache2.service - The Apache HTTP Server...
Feb 18 15:05:46 myaa6bd apachectl[785]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127>
Feb 18 15:05:46 myaa6bd systemd[1]: Started apache2.service - The Apache HTTP Server.
lines 1-19/19 (END)

I viewed /var/tmp/build-dahdi.txt and did not see any errors.  I did see 
### DAHDI installed successfully
and
### DAHDI tools installed successfully

but no error messages near the end of the file.

**Comment by Allan-N** [comment]
I believe that the last time I built/installed on my RPi4 I had chosen the "Raspberry Pi OS Lite (64-bit)" image but the full image should also be good.

From the logs you have provided it "looks" like there's an issue with DAHDI ... and that's needed by Asterisk.

I'm not sure what to suggest at the moment.  What I will try to do this week is start with a fresh install on my RPi and see if I run into any issues.  I will keep you posted.

**Comment by hwdornbush** [comment]
OK, thank you, and if there is anything else I need to test, please let me
know.

--Bill AA6BD

**Comment by Allan-N** [comment]
This morning I started my RPI4 with a fresh image.  I followed the steps I outlined on the GitHub page and, as you found, noticed that asterisk was not starting.  Yay, I repro'd the issue that you reported.

But, I did skip one step in my instructions.  Just below the "Initial Setup (Ubuntu...)" commands there's a note to reboot your device if the `sudo apt upgrade` step resulted in the kernel being updated.  That comment actually applies to all of the OS variants and I need to make that more pronounced in the instructions.  I mention this because after I rebooted my device I went back, exec'd the `./asl-install` command again, and repeated all of the build/install steps (1-10).  Now, when I check the services I see that asterisk is running :-)

So, can you make another build/install pass on your device and see if that gets you going.  Please let me know.

**Comment by hwdornbush** [comment]
I re-installed using RPi OS Lite 64 bit, and the installation worked.
Thanks.

This version of ASL appears to be different from the one I use from
hamvoip.org, and I had a struggle getting most things working.  I don't
have the COS LED working on my SHARI as the parameters documented to change
in "rpt.conf" are missing in this version.

**Comment by Allan-N** [comment]
> I re-installed using RPi OS Lite 64 bit, and the installation worked.

Excellent !!!

I'm going to keep this issue open for a bit with the goal of trying to identify when a reboot is needed.  At the very least, I will update the documentation on the installation process.

I agree that there are differences between ASL-Asterisk and HamVOIP.  But, given that both are based on "Asterisk", you should be able to make the needed changes to the "rpt.conf" file.
